# Mongodb configuration
spring.data.mongodb.uri=mongodb://localhost:27017/resumebuilder

# Email configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a307d5001@smtp-brevo.com
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=zzangsally@gmail.com

# Applicatuib info
app.base.url=http://localhost:8080

# Cloudinary information
cloudinary.cloud-name=dmxnml9p1
cloudinary.api-key=869928396498636
cloudinary.api-secret=${CLOUDINARY_SECRET_KEY}

# JWT Configuration
jwt.secret=qL33iK1IloqIgCRmEIJXf5wtNwZcW5qfmplVvFtk0Hz
jwt.expiration=604800000